a=int(input("Enter any number: "))
b=int(input("Enter any number: "))
print("Base function Convesion")
print(f"The Binary for A is: {bin(a)}")
print(f"The Binary for B is: {bin(b)}")
print(f"The Octal for A is: {oct(a)}")
print(f"The Octal for B is: {oct(b)}")
print(f"The Hexadecimal for A is: {hex(a)}")
print(f"The Hexadecimal for B is: {hex(b)}")
print(f"The Character for A is: {chr(a)}")
print(f"The Character for B is: {chr(b)}")
print(f"The Float for A is: {float(a)}")
print(f"The Float for B is: {float(b)}")
